language: node_js
node_js:
  - "10"
  - "12"
  - "14"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm test
deploy:
  - provider: script
    cleanup: false
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
